namespace XmasTree.Common;

public enum TreeLight
{
    [Display(Name = "Star")]
    STAR = 2,
    [Display(Name = "1")]
    ONE = 4,
    [Display(Name = "2")]
    TWO = 15,
    [Display(Name = "3")]
    THREE = 13,
    [Display(Name = "4")]
    FOUR = 21,
    [Display(Name = "5")]
    FIVE = 25,
    [Display(Name = "6")]
    SIX = 8,
    [Display(Name = "7")]
    SEVEN = 5,
    [Display(Name = "8")]
    EIGHT = 10,
    [Display(Name = "9")]
    NINE = 16,
    [Display(Name = "10")]
    TEN = 17,
    [Display(Name = "11")]
    ELEVEN = 27,
    [Display(Name = "12")]
    TWELVE = 26,
    [Display(Name = "13")]
    THIRTEEN = 24,
    [Display(Name = "14")]
    FOURTEEN = 9,
    [Display(Name = "15")]
    FIFTEEN = 12,
    [Display(Name = "16")]
    SIXTEEN = 6,
    [Display(Name = "17")]
    SEVENTEEN = 20,
    [Display(Name = "18")]
    EIGHTEEN = 19,
    [Display(Name = "19")]
    NINETEEN = 14,
    [Display(Name = "20")]
    TWENTY = 18,
    [Display(Name = "21")]
    TWENTYONE = 11,
    [Display(Name = "22")]
    TWENTYTWO = 7,
    [Display(Name = "23")]
    TWENTYTHREE = 23,
    [Display(Name = "24")]
    TWENTYFOUR = 22
}
